// <auto-generated />
using System;
using IronLeague.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251217063915_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IronLeague.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("IronLeague.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MatchesDrawn")
                        .HasColumnType("int");

                    b.Property<int>("MatchesLost")
                        .HasColumnType("int");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("MatchesWon")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrophiesWon")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("IronLeague.Entities.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueInstanceId");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("IronLeague.Entities.CompetitionTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupPoints")
                        .HasColumnType("int");

                    b.Property<bool>("IsEliminated")
                        .HasColumnType("bit");

                    b.Property<Guid>("TeamInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("TeamInstanceId");

                    b.ToTable("CompetitionTeams");
                });

            modelBuilder.Entity("IronLeague.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AssistBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CanBeCancelledFree")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("GoalBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ReleaseClause")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SigningBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WeeklyWage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("IronLeague.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExchangeRateToEur")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("IronLeague.Entities.Fixture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MatchDay")
                        .HasColumnType("int");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Round")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("ScheduledDate");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("IronLeague.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("IronLeague.Entities.GovernanceSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChemistryCombination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChemistryCurve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ChemistryWeight")
                        .HasColumnType("real");

                    b.Property<string>("CrowdCombination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrowdCurve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CrowdWeight")
                        .HasColumnType("real");

                    b.Property<string>("ExperienceCurve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ExperienceWeight")
                        .HasColumnType("real");

                    b.Property<string>("FormCurve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("FormWeight")
                        .HasColumnType("real");

                    b.Property<string>("LanguageCombination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCurve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("LanguageWeight")
                        .HasColumnType("real");

                    b.Property<string>("ManagerReputationCurve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ManagerReputationWeight")
                        .HasColumnType("real");

                    b.Property<string>("MoraleCombination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoraleCurve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MoraleWeight")
                        .HasColumnType("real");

                    b.Property<string>("PresetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PressureCombination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PressureCurve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PressureWeight")
                        .HasColumnType("real");

                    b.Property<string>("RefereeCombination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefereeCurve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("RefereeWeight")
                        .HasColumnType("real");

                    b.Property<float>("RngChaosWeight")
                        .HasColumnType("real");

                    b.Property<string>("ScandalCurve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ScandalWeight")
                        .HasColumnType("real");

                    b.Property<string>("SpeechCombination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeechCurve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SpeechWeight")
                        .HasColumnType("real");

                    b.Property<string>("WeatherCombination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeatherCurve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("WeatherWeight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("GovernanceSettings");
                });

            modelBuilder.Entity("IronLeague.Entities.InGameInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinReputationRequired")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InGameInstructions");
                });

            modelBuilder.Entity("IronLeague.Entities.InternationalBreak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InternationalBreaks");
                });

            modelBuilder.Entity("IronLeague.Entities.InternationalCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BreakEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BreakStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InjuryDays")
                        .HasColumnType("int");

                    b.Property<Guid>("InternationalTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PlayerReturned")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("InternationalTeamId");

                    b.HasIndex("PlayerId");

                    b.ToTable("InternationalCalls");
                });

            modelBuilder.Entity("IronLeague.Entities.InternationalTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("FifaRanking")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("ManagerId");

                    b.ToTable("InternationalTeams");
                });

            modelBuilder.Entity("IronLeague.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("MaxTeams")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PromotesToLeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PromotionSpots")
                        .HasColumnType("int");

                    b.Property<Guid?>("RelegatesFromLeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RelegationSpots")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("PromotesToLeagueId")
                        .IsUnique()
                        .HasFilter("[PromotesToLeagueId] IS NOT NULL");

                    b.HasIndex("RelegatesFromLeagueId")
                        .IsUnique()
                        .HasFilter("[RelegatesFromLeagueId] IS NOT NULL");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("IronLeague.Entities.LeagueInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaseLeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentSeason")
                        .HasColumnType("int");

                    b.Property<Guid>("GovernanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaseLeagueId");

                    b.HasIndex("GovernanceId")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("LeagueInstances");
                });

            modelBuilder.Entity("IronLeague.Entities.LeagueInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("InvitedUserId");

                    b.HasIndex("LeagueInstanceId");

                    b.ToTable("LeagueInvites");
                });

            modelBuilder.Entity("IronLeague.Entities.LeagueTeamInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("int");

                    b.Property<bool>("IsControlledByPlayer")
                        .HasColumnType("bit");

                    b.Property<Guid>("LeagueInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseTeamId");

                    b.HasIndex("LeagueInstanceId");

                    b.HasIndex("ManagerId");

                    b.ToTable("LeagueTeamInstances");
                });

            modelBuilder.Entity("IronLeague.Entities.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurrentTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LeagueInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Mental")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PersonalBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Physical")
                        .HasColumnType("int");

                    b.Property<int>("Reputation")
                        .HasColumnType("int");

                    b.Property<int>("Technical")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LeagueInstanceId");

                    b.HasIndex("UserId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("IronLeague.Entities.ManagerLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Proficiency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("ManagerLanguages");
                });

            modelBuilder.Entity("IronLeague.Entities.ManagerTrophy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompetitionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<string>("TrophyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WonAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("ManagerTrophies");
                });

            modelBuilder.Entity("IronLeague.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attendance")
                        .HasColumnType("int");

                    b.Property<string>("AwayFormation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AwayPausesUsed")
                        .HasColumnType("int");

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwaySpeechesUsed")
                        .HasColumnType("int");

                    b.Property<string>("AwayTactics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentTick")
                        .HasColumnType("int");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HomeFormation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomeHomeSpeechesUsed")
                        .HasColumnType("int");

                    b.Property<int>("HomePausesUsed")
                        .HasColumnType("int");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<string>("HomeTactics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PauseStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PausedByManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("RngSeed")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalTicks")
                        .HasColumnType("int");

                    b.Property<string>("Weather")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("IronLeague.Entities.MatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHomeTeam")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImportantEvent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsKeyEvent")
                        .HasColumnType("bit");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("PositionX")
                        .HasColumnType("real");

                    b.Property<float?>("PositionY")
                        .HasColumnType("real");

                    b.Property<Guid?>("PrimaryPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SecondaryPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tick")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PrimaryPlayerId");

                    b.HasIndex("SecondaryPlayerId");

                    b.ToTable("MatchEvents");
                });

            modelBuilder.Entity("IronLeague.Entities.MatchState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("AwayMomentum")
                        .HasColumnType("real");

                    b.Property<Guid?>("BallPossessionPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("BallX")
                        .HasColumnType("real");

                    b.Property<float>("BallY")
                        .HasColumnType("real");

                    b.Property<float>("HomeMomentum")
                        .HasColumnType("real");

                    b.Property<bool>("IsHomeTeamPossession")
                        .HasColumnType("bit");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlayerPositionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tick")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "Tick");

                    b.ToTable("MatchStates");
                });

            modelBuilder.Entity("IronLeague.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("IronLeague.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentAbility")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Defending")
                        .HasColumnType("int");

                    b.Property<int>("Dribbling")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fitness")
                        .HasColumnType("int");

                    b.Property<int>("Form")
                        .HasColumnType("int");

                    b.Property<bool>("IsLegend")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpecialLegend")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LoanedFromTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MarketValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Morale")
                        .HasColumnType("int");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Pace")
                        .HasColumnType("int");

                    b.Property<int>("Passing")
                        .HasColumnType("int");

                    b.Property<int>("Physical")
                        .HasColumnType("int");

                    b.Property<int>("Potential")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Shooting")
                        .HasColumnType("int");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsLegend");

                    b.HasIndex("LoanedFromTeamId");

                    b.HasIndex("Nationality");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("IronLeague.Entities.PlayerAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerAttributes");
                });

            modelBuilder.Entity("IronLeague.Entities.PlayerLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsNative")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerLanguages");
                });

            modelBuilder.Entity("IronLeague.Entities.PlayerMatchStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("DistanceCovered")
                        .HasColumnType("int");

                    b.Property<int>("Fouls")
                        .HasColumnType("int");

                    b.Property<int>("FoulsSuffered")
                        .HasColumnType("int");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<int>("Interceptions")
                        .HasColumnType("int");

                    b.Property<bool>("IsHomeTeam")
                        .HasColumnType("bit");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("Passes")
                        .HasColumnType("int");

                    b.Property<int>("PassesCompleted")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("RedCards")
                        .HasColumnType("int");

                    b.Property<int>("Shots")
                        .HasColumnType("int");

                    b.Property<int>("ShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int>("Sprints")
                        .HasColumnType("int");

                    b.Property<int>("Tackles")
                        .HasColumnType("int");

                    b.Property<int>("TacklesWon")
                        .HasColumnType("int");

                    b.Property<int>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerMatchStats");
                });

            modelBuilder.Entity("IronLeague.Entities.PlayerTrainingResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttributeChange")
                        .HasColumnType("int");

                    b.Property<string>("AttributeImproved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FitnessChange")
                        .HasColumnType("int");

                    b.Property<int>("MoraleChange")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrainingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("PlayerTrainingResults");
                });

            modelBuilder.Entity("IronLeague.Entities.PressEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FanMoodImpact")
                        .HasColumnType("int");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LeagueInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MoraleImpact")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReputationImpact")
                        .HasColumnType("int");

                    b.Property<Guid?>("TargetManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TargetPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TargetTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueInstanceId");

                    b.HasIndex("TargetManagerId");

                    b.HasIndex("TargetPlayerId");

                    b.HasIndex("TargetTeamId");

                    b.ToTable("PressEvents");
                });

            modelBuilder.Entity("IronLeague.Entities.SaveExport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExportedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExportedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExportedByUserId");

                    b.HasIndex("LeagueInstanceId");

                    b.ToTable("SaveExports");
                });

            modelBuilder.Entity("IronLeague.Entities.Speech", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Backfired")
                        .HasColumnType("bit");

                    b.Property<float>("EffectStrength")
                        .HasColumnType("real");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResultDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TargetPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tick")
                        .HasColumnType("int");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("MatchId");

                    b.HasIndex("TargetPlayerId");

                    b.ToTable("Speeches");
                });

            modelBuilder.Entity("IronLeague.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ability")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("IronLeague.Entities.Tactic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CounterAttack")
                        .HasColumnType("bit");

                    b.Property<int>("DefensiveLine")
                        .HasColumnType("int");

                    b.Property<bool>("DirectPassing")
                        .HasColumnType("bit");

                    b.Property<string>("Formation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HighPress")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ParkTheBus")
                        .HasColumnType("bit");

                    b.Property<bool>("PlayOutFromBack")
                        .HasColumnType("bit");

                    b.Property<string>("PlayerInstructionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pressing")
                        .HasColumnType("int");

                    b.Property<string>("SetPieceRoutinesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeamInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tempo")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamInstanceId");

                    b.ToTable("Tactics");
                });

            modelBuilder.Entity("IronLeague.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FanLoyalty")
                        .HasColumnType("int");

                    b.Property<int>("FanMood")
                        .HasColumnType("int");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MerchandiseIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SponsorIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StadiumCapacity")
                        .HasColumnType("int");

                    b.Property<string>("StadiumName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TicketIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TransferBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TvIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WageBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasFilter("[ManagerId] IS NOT NULL");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("IronLeague.Entities.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FocusAttribute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TeamInstanceId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("IronLeague.Entities.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("FromTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLoan")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LoanBuyOptionFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LoanEndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LoanFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("LoanHasBuyOption")
                        .HasColumnType("bit");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ToTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FromTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Status");

                    b.HasIndex("ToTeamId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("IronLeague.Entities.TransferOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCounterOffer")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OfferedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OfferedContractYears")
                        .HasColumnType("int");

                    b.Property<decimal>("OfferedFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OfferedWage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransferId");

                    b.ToTable("TransferOffers");
                });

            modelBuilder.Entity("IronLeague.Entities.YouthAcademy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastIntakeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("ScoutingRange")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrainingQuality")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("YouthAcademies");
                });

            modelBuilder.Entity("IronLeague.Entities.YouthPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentAbility")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPromoted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PotentialMax")
                        .HasColumnType("int");

                    b.Property<int>("PotentialMin")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryPosition")
                        .HasColumnType("int");

                    b.Property<Guid>("YouthAcademyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("YouthAcademyId");

                    b.ToTable("YouthPlayers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IronLeague.Entities.Competition", b =>
                {
                    b.HasOne("IronLeague.Entities.LeagueInstance", "LeagueInstance")
                        .WithMany("Competitions")
                        .HasForeignKey("LeagueInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeagueInstance");
                });

            modelBuilder.Entity("IronLeague.Entities.CompetitionTeam", b =>
                {
                    b.HasOne("IronLeague.Entities.Competition", "Competition")
                        .WithMany("Teams")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.LeagueTeamInstance", "TeamInstance")
                        .WithMany()
                        .HasForeignKey("TeamInstanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("TeamInstance");
                });

            modelBuilder.Entity("IronLeague.Entities.Contract", b =>
                {
                    b.HasOne("IronLeague.Entities.Player", "Player")
                        .WithOne("Contract")
                        .HasForeignKey("IronLeague.Entities.Contract", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("IronLeague.Entities.Fixture", b =>
                {
                    b.HasOne("IronLeague.Entities.LeagueTeamInstance", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.Competition", "Competition")
                        .WithMany("Fixtures")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.LeagueTeamInstance", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("Competition");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("IronLeague.Entities.Friendship", b =>
                {
                    b.HasOne("IronLeague.Entities.AppUser", "User1")
                        .WithMany("FriendshipsInitiated")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.AppUser", "User2")
                        .WithMany("FriendshipsReceived")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("IronLeague.Entities.InternationalCall", b =>
                {
                    b.HasOne("IronLeague.Entities.InternationalTeam", "InternationalTeam")
                        .WithMany("CallUps")
                        .HasForeignKey("InternationalTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InternationalTeam");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IronLeague.Entities.InternationalTeam", b =>
                {
                    b.HasOne("IronLeague.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Country");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("IronLeague.Entities.League", b =>
                {
                    b.HasOne("IronLeague.Entities.Country", "Country")
                        .WithMany("Leagues")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.League", "PromotesToLeague")
                        .WithOne()
                        .HasForeignKey("IronLeague.Entities.League", "PromotesToLeagueId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IronLeague.Entities.League", "RelegatesFromLeague")
                        .WithOne()
                        .HasForeignKey("IronLeague.Entities.League", "RelegatesFromLeagueId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Country");

                    b.Navigation("PromotesToLeague");

                    b.Navigation("RelegatesFromLeague");
                });

            modelBuilder.Entity("IronLeague.Entities.LeagueInstance", b =>
                {
                    b.HasOne("IronLeague.Entities.League", "BaseLeague")
                        .WithMany()
                        .HasForeignKey("BaseLeagueId");

                    b.HasOne("IronLeague.Entities.GovernanceSettings", "Governance")
                        .WithOne()
                        .HasForeignKey("IronLeague.Entities.LeagueInstance", "GovernanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaseLeague");

                    b.Navigation("Governance");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("IronLeague.Entities.LeagueInvite", b =>
                {
                    b.HasOne("IronLeague.Entities.AppUser", null)
                        .WithMany("LeagueInvites")
                        .HasForeignKey("AppUserId");

                    b.HasOne("IronLeague.Entities.AppUser", "InvitedByUser")
                        .WithMany("LeagueInvitesSent")
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.AppUser", "InvitedUser")
                        .WithMany("LeagueInvitesReceived")
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.LeagueInstance", "LeagueInstance")
                        .WithMany("Invites")
                        .HasForeignKey("LeagueInstanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InvitedByUser");

                    b.Navigation("InvitedUser");

                    b.Navigation("LeagueInstance");
                });

            modelBuilder.Entity("IronLeague.Entities.LeagueTeamInstance", b =>
                {
                    b.HasOne("IronLeague.Entities.Team", "BaseTeam")
                        .WithMany()
                        .HasForeignKey("BaseTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.LeagueInstance", "LeagueInstance")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BaseTeam");

                    b.Navigation("LeagueInstance");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("IronLeague.Entities.Manager", b =>
                {
                    b.HasOne("IronLeague.Entities.LeagueInstance", "LeagueInstance")
                        .WithMany("Managers")
                        .HasForeignKey("LeagueInstanceId");

                    b.HasOne("IronLeague.Entities.AppUser", "User")
                        .WithMany("Managers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeagueInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IronLeague.Entities.ManagerLanguage", b =>
                {
                    b.HasOne("IronLeague.Entities.Manager", "Manager")
                        .WithMany("Languages")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("IronLeague.Entities.ManagerTrophy", b =>
                {
                    b.HasOne("IronLeague.Entities.Manager", "Manager")
                        .WithMany("Trophies")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("IronLeague.Entities.Match", b =>
                {
                    b.HasOne("IronLeague.Entities.Fixture", "Fixture")
                        .WithOne("Match")
                        .HasForeignKey("IronLeague.Entities.Match", "FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("IronLeague.Entities.MatchEvent", b =>
                {
                    b.HasOne("IronLeague.Entities.Match", "Match")
                        .WithMany("Events")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.Player", "PrimaryPlayer")
                        .WithMany()
                        .HasForeignKey("PrimaryPlayerId");

                    b.HasOne("IronLeague.Entities.Player", "SecondaryPlayer")
                        .WithMany()
                        .HasForeignKey("SecondaryPlayerId");

                    b.Navigation("Match");

                    b.Navigation("PrimaryPlayer");

                    b.Navigation("SecondaryPlayer");
                });

            modelBuilder.Entity("IronLeague.Entities.MatchState", b =>
                {
                    b.HasOne("IronLeague.Entities.Match", "Match")
                        .WithMany("States")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("IronLeague.Entities.Notification", b =>
                {
                    b.HasOne("IronLeague.Entities.AppUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IronLeague.Entities.Player", b =>
                {
                    b.HasOne("IronLeague.Entities.Team", "LoanedFromTeam")
                        .WithMany()
                        .HasForeignKey("LoanedFromTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IronLeague.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.Navigation("LoanedFromTeam");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("IronLeague.Entities.PlayerAttribute", b =>
                {
                    b.HasOne("IronLeague.Entities.Player", "Player")
                        .WithMany("Attributes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IronLeague.Entities.PlayerLanguage", b =>
                {
                    b.HasOne("IronLeague.Entities.Player", "Player")
                        .WithMany("Languages")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IronLeague.Entities.PlayerMatchStats", b =>
                {
                    b.HasOne("IronLeague.Entities.Match", "Match")
                        .WithMany("PlayerStats")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.Player", "Player")
                        .WithMany("MatchStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IronLeague.Entities.PlayerTrainingResult", b =>
                {
                    b.HasOne("IronLeague.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.TrainingSession", "TrainingSession")
                        .WithMany("Results")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("IronLeague.Entities.PressEvent", b =>
                {
                    b.HasOne("IronLeague.Entities.LeagueInstance", "LeagueInstance")
                        .WithMany()
                        .HasForeignKey("LeagueInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.Manager", "TargetManager")
                        .WithMany()
                        .HasForeignKey("TargetManagerId");

                    b.HasOne("IronLeague.Entities.Player", "TargetPlayer")
                        .WithMany()
                        .HasForeignKey("TargetPlayerId");

                    b.HasOne("IronLeague.Entities.Team", "TargetTeam")
                        .WithMany()
                        .HasForeignKey("TargetTeamId");

                    b.Navigation("LeagueInstance");

                    b.Navigation("TargetManager");

                    b.Navigation("TargetPlayer");

                    b.Navigation("TargetTeam");
                });

            modelBuilder.Entity("IronLeague.Entities.SaveExport", b =>
                {
                    b.HasOne("IronLeague.Entities.AppUser", "ExportedByUser")
                        .WithMany()
                        .HasForeignKey("ExportedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.LeagueInstance", "LeagueInstance")
                        .WithMany()
                        .HasForeignKey("LeagueInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExportedByUser");

                    b.Navigation("LeagueInstance");
                });

            modelBuilder.Entity("IronLeague.Entities.Speech", b =>
                {
                    b.HasOne("IronLeague.Entities.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.Player", "TargetPlayer")
                        .WithMany()
                        .HasForeignKey("TargetPlayerId");

                    b.Navigation("Manager");

                    b.Navigation("Match");

                    b.Navigation("TargetPlayer");
                });

            modelBuilder.Entity("IronLeague.Entities.Staff", b =>
                {
                    b.HasOne("IronLeague.Entities.Team", "Team")
                        .WithMany("Staff")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("IronLeague.Entities.Tactic", b =>
                {
                    b.HasOne("IronLeague.Entities.LeagueTeamInstance", "TeamInstance")
                        .WithMany()
                        .HasForeignKey("TeamInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamInstance");
                });

            modelBuilder.Entity("IronLeague.Entities.Team", b =>
                {
                    b.HasOne("IronLeague.Entities.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.Manager", "Manager")
                        .WithOne("CurrentTeam")
                        .HasForeignKey("IronLeague.Entities.Team", "ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("League");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("IronLeague.Entities.TrainingSession", b =>
                {
                    b.HasOne("IronLeague.Entities.LeagueTeamInstance", "TeamInstance")
                        .WithMany()
                        .HasForeignKey("TeamInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamInstance");
                });

            modelBuilder.Entity("IronLeague.Entities.Transfer", b =>
                {
                    b.HasOne("IronLeague.Entities.Team", "FromTeam")
                        .WithMany()
                        .HasForeignKey("FromTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.Team", "ToTeam")
                        .WithMany()
                        .HasForeignKey("ToTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FromTeam");

                    b.Navigation("Player");

                    b.Navigation("ToTeam");
                });

            modelBuilder.Entity("IronLeague.Entities.TransferOffer", b =>
                {
                    b.HasOne("IronLeague.Entities.Transfer", "Transfer")
                        .WithMany()
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("IronLeague.Entities.YouthAcademy", b =>
                {
                    b.HasOne("IronLeague.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("IronLeague.Entities.YouthPlayer", b =>
                {
                    b.HasOne("IronLeague.Entities.YouthAcademy", "YouthAcademy")
                        .WithMany("YouthPlayers")
                        .HasForeignKey("YouthAcademyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YouthAcademy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("IronLeague.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("IronLeague.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("IronLeague.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("IronLeague.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLeague.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("IronLeague.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IronLeague.Entities.AppUser", b =>
                {
                    b.Navigation("FriendshipsInitiated");

                    b.Navigation("FriendshipsReceived");

                    b.Navigation("LeagueInvites");

                    b.Navigation("LeagueInvitesReceived");

                    b.Navigation("LeagueInvitesSent");

                    b.Navigation("Managers");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("IronLeague.Entities.Competition", b =>
                {
                    b.Navigation("Fixtures");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("IronLeague.Entities.Country", b =>
                {
                    b.Navigation("Leagues");
                });

            modelBuilder.Entity("IronLeague.Entities.Fixture", b =>
                {
                    b.Navigation("Match");
                });

            modelBuilder.Entity("IronLeague.Entities.InternationalTeam", b =>
                {
                    b.Navigation("CallUps");
                });

            modelBuilder.Entity("IronLeague.Entities.League", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("IronLeague.Entities.LeagueInstance", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("Invites");

                    b.Navigation("Managers");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("IronLeague.Entities.Manager", b =>
                {
                    b.Navigation("CurrentTeam");

                    b.Navigation("Languages");

                    b.Navigation("Trophies");
                });

            modelBuilder.Entity("IronLeague.Entities.Match", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("PlayerStats");

                    b.Navigation("States");
                });

            modelBuilder.Entity("IronLeague.Entities.Player", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Contract");

                    b.Navigation("Languages");

                    b.Navigation("MatchStats");
                });

            modelBuilder.Entity("IronLeague.Entities.Team", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("IronLeague.Entities.TrainingSession", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("IronLeague.Entities.YouthAcademy", b =>
                {
                    b.Navigation("YouthPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
